---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install apache2
  apt: 
    name: apache2
    state: latest 

- name: Enabling mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - restart apache2
    

